config/routes.rb
Rails.application.routes.draw do

  resources :volunteers

  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :organizations
  resources :gigs
  resources :cities, only: :index
  resources :candidatures
  resources :reviews

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user
      can :read, Volunteer
      can :read, Organization
      can :manage, Volunteer, user_id: user.id
      can :manage, Organization, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidature.rb
class Candidature < ApplicationRecord
  belongs_to :gig
  belongs_to :volunteer
  validates :gig, :volunteer, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  validates :name, :state, presence: true
  validates_inclusion_of :capital, in: [true, false]

  def to_s
    "#{name} / #{state.acronym}"
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :organization
  validates :organization, :title, :description, :start_date, :end_date, :number_of_available_candidatures, presence: true
  has_many :candidatures
end

app/models/organization.rb
class Organization < ApplicationRecord
  include PolymorphicType
  self.per_page = 10
  belongs_to :user
  belongs_to :city
  has_many :gigs
  has_many :reviews, as: :reviewable
  validates :name, :phone, :description, :address, :user, :city, presence: true
end

app/models/region.rb
class Region < ApplicationRecord
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
  validates :reviewable, :reviewable_type, :note, presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :region
  validates :name, :acronym, :region, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum kind: [:Volunteer, :Organization]
  has_one :organization
  has_one :volunteer
  validates :kind, presence: true
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  include PolymorphicType
  belongs_to :user
  belongs_to :city
  has_many :candidatures
  has_many :reviews, as: :reviewable
  validates :name,:phone,:user,:city, presence: true
end

app/controllers/candidatures_controller.rb
class CandidaturesController < ApplicationController
  before_action :set_gig
  before_action :set_candidature, only: [:show, :edit, :update, :destroy]

  def index
    @candidatures = @gig.candidatures.all.paginate(page: params[:page])
  end

  def show
  end

  def new
    @candidature = @gig.candidatures.build
  end

  def edit
  end

  def create
    @candidature = @gig.candidatures.build(candidature_params)

    respond_to do |format|
      if @candidature.save
        format.html { redirect_to @candidature, notice: 'Candidature was successfully created.' }
        format.json { render :show, status: :created, location: @candidature }
      else
        format.html { render :new }
        format.json { render json: @candidature.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @candidature.update(candidature_params)
        format.html { redirect_to @candidature, notice: 'Candidature was successfully updated.' }
        format.json { render :show, status: :ok, location: @candidature }
      else
        format.html { render :edit }
        format.json { render json: @candidature.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @candidature.destroy
    respond_to do |format|
      format.html { redirect_to candidatures_url, notice: 'Candidature was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_gig
      @gig = Gig.find(params[:gig_id])
    end

    def set_candidature
      @candidature = Candidature.find(params[:id])
    end

    def candidature_params
      params.require(:candidature).permit(:gig_id, :volunteer_id, :introduction_letter, :accepted)
    end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all.paginate(page: params[:page])

    unless params[:q].to_s.empty?
     like_query = "%#{params[:q].upcase}%"
     @cities = @cities.where("upper(name) like ? ", like_query)
   end
 end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_organization
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  def index
    @gigs = @organization.gigs.paginate(page: params[:page])
  end

  def show
  end

  def new
    @gig = @organization.gigs.build
  end

  def edit
  end

  def create
    @gig = @organization.gigs.build(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_organization
      @organization = Organization.find(params[:organization_id])
    end

    def set_gig
      @gig = @organization.gigs.find(params[:id])
    end

    def gig_params
      params.require(:gig).permit(:title, :description, :start_date, :end_date, :number_of_available_candidatures, :available, :organization_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidatures_helper.rb
module CandidaturesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/candidatures/_form.html.erb
<%= form_for(candidature) do |f| %>
  <% if candidature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidature.errors.count, "error") %> prohibited this candidature from being saved:</h2>

      <ul>
      <% candidature.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :introduction_letter %>
    <%= f.text_area :introduction_letter %>
  </div>

  <div class="field">
    <%= f.label :accepted %>
    <%= f.check_box :accepted %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/candidatures/edit.html.erb
<h1>Editing Candidature</h1>

<%= render 'form', candidature: @candidature %>

<%= link_to 'Show', @candidature %> |
<%= link_to 'Back', candidatures_path %>

app/views/candidatures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidatures</h1>

<table>
  <thead>
    <tr>
      <th>Introduction letter</th>
      <th>Accepted</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidatures.each do |candidature| %>
      <tr>
        <td><%= candidature.introduction_letter %></td>
        <td><%= candidature.accepted %></td>
        <td><%= link_to 'Show', candidature %></td>
        <td><%= link_to 'Edit', edit_candidature_path(candidature) %></td>
        <td><%= link_to 'Destroy', candidature, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidature', new_candidature_path %>

app/views/candidatures/new.html.erb
<h1>New Candidature</h1>

<%= render 'form', candidature: @candidature %>

<%= link_to 'Back', candidatures_path %>

app/views/candidatures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Introduction letter:</strong>
  <%= @candidature.introduction_letter %>
</p>

<p>
  <strong>Accepted:</strong>
  <%= @candidature.accepted %>
</p>

<%= link_to 'Edit', edit_candidature_path(@candidature) %> |
<%= link_to 'Back', candidatures_path %>