config/routes.rb
Rails.application.routes.draw do

  resources :volunteers

  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :organizations
  resources :gigs
  resources :cities, only: :index
  resources :candidatures
  resources :reviews

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user
      can :read, Volunteer
      can :read, Organization
      can :manage, Volunteer, user_id: user.id
      can :manage, Organization, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidature.rb
class Candidature < ApplicationRecord
  belongs_to :gig
  belongs_to :volunteer
  validates :gig, :volunteer, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  validates :name, :state, presence: true
  validates_inclusion_of :capital, in: [true, false]

  def to_s
    "#{name} / #{state.acronym}"
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :organization
  validates :organization, :title, :description, :start_date, :end_date, :number_of_available_candidatures, presence: true
  has_many :candidatures
end

app/models/organization.rb
class Organization < ApplicationRecord
  include PolymorphicType
  self.per_page = 10
  belongs_to :user
  belongs_to :city
  has_many :gigs
  has_many :reviews, as: :reviewable
  validates :name, :phone, :description, :address, :user, :city, presence: true
end

app/models/region.rb
class Region < ApplicationRecord
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
  validates :reviewable, :reviewable_type, :note, presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :region
  validates :name, :acronym, :region, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum kind: [:Volunteer, :Organization]
  has_one :organization
  has_one :volunteer
  validates :kind, presence: true
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  include PolymorphicType
  belongs_to :user
  belongs_to :city
  has_many :candidatures
  has_many :reviews, as: :reviewable
  validates :name,:phone,:user,:city, presence: true
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def index
    @cities = City.all.paginate(page: params[:page])

    unless params[:q].to_s.empty?
     like_query = "%#{params[:q].upcase}%"
     @cities = @cities.where("upper(name) like ? ", like_query)
   end
 end

end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_organization
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  def index
    @gigs = @organization.gigs.paginate(page: params[:page])
  end

  def show
  end

  def new
    @gig = @organization.gigs.build
  end

  def edit
  end

  def create
    @gig = @organization.gigs.build(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_organization
      @organization = Organization.find(params[:organization_id])
    end

    def set_gig
      @gig = @organization.gigs.find(params[:id])
    end

    def gig_params
      params.require(:gig).permit(:title, :description, :start_date, :end_date, :number_of_available_candidatures, :available, :organization_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all.paginate(:page => params[:page])
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :phone, :description, :address, :user_id, :city_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidatures_helper.rb
module CandidaturesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/organizations/_form.html.erb
<%= form_for(organization) do |f| %>
  <% if organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% organization.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organizations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.name %></td>
        <td><%= organization.phone %></td>
        <td><%= organization.description %></td>
        <td><%= link_to 'Show', organization %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization) %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @organizations %>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @organization.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @organization.phone %>
</p>

<p>
  <strong>Description:</strong>
  <%= @organization.description %>
</p>

<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>