config/routes.rb
Rails.application.routes.draw do

  resources :volunteers

  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"

  resources :organizations
  resources :gigs
  resources :cities, only: :index
  resources :candidatures
  resources :reviews

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user
      can :read, Volunteer
      can :read, Organization
      can :manage, Volunteer, user_id: user.id
      can :manage, Organization, user_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidature.rb
class Candidature < ApplicationRecord
  belongs_to :gig
  belongs_to :volunteer
  validates :gig, :volunteer, presence: true
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state
  validates :name, :state, presence: true
  validates_inclusion_of :capital, in: [true, false]

  def to_s
    "#{name} / #{state.acronym}"
  end
end

app/models/gig.rb
class Gig < ApplicationRecord
  belongs_to :organization
  validates :organization, :title, :description, :start_date, :end_date, :number_of_available_candidatures, presence: true
  has_many :candidatures
end

app/models/organization.rb
class Organization < ApplicationRecord
  include PolymorphicType
  self.per_page = 10
  belongs_to :user
  belongs_to :city
  has_many :gigs
  has_many :reviews, as: :reviewable
  validates :name, :phone, :description, :address, :user, :city, presence: true
end

app/models/region.rb
class Region < ApplicationRecord
  validates :name, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewable, polymorphic: true
  validates :reviewable, :reviewable_type, :note, presence: true
end

app/models/state.rb
class State < ApplicationRecord
  belongs_to :region
  validates :name, :acronym, :region, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum kind: [:Volunteer, :Organization]
  has_one :organization
  has_one :volunteer
  validates :kind, presence: true
end

app/models/volunteer.rb
class Volunteer < ApplicationRecord
  include PolymorphicType
  belongs_to :user
  belongs_to :city
  has_many :candidatures
  has_many :reviews, as: :reviewable
  validates :name,:phone,:user,:city, presence: true
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_organization
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  def index
    @gigs = @organization.gigs.paginate(page: params[:page])
  end

  def show
  end

  def new
    @gig = @organization.gigs.build
  end

  def edit
  end

  def create
    @gig = @organization.gigs.build(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render :show, status: :created, location: @gig }
      else
        format.html { render :new }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { render :show, status: :ok, location: @gig }
      else
        format.html { render :edit }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url, notice: 'Gig was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_organization
      @organization = Organization.find(params[:organization_id])
    end

    def set_gig
      @gig = @organization.gigs.find(params[:id])
    end

    def gig_params
      params.require(:gig).permit(:title, :description, :start_date, :end_date, :number_of_available_candidatures, :available, :organization_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_reviewable
  before_action :set_review, only: [:show, :edit, :update, :destroy]

  def index
    @reviews = @reviewable.reviews.all.paginate(page: params[:page])
  end

  def show
  end

  def new
    @review = @reviewable.reviews.build
  end

  def edit
  end

  def create
    @review = @reviewable.reviews.build(review_params)

    respond_to do |format|
      if @review.save
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_reviewable
      type = params[:reviewable_type]
      if type == 'Volunteer'
        @reviewable = Volunteer.find(params[:reviewable_id])
      else
        @reviewable = Organization.find(params[:reviewable_id])
      end
    end

    def set_review
      @review = Review.find(params[:id])
    end

    def review_params
      params.require(:review).permit(:reviewable_id, :reviewable_type, :note, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/candidatures_helper.rb
module CandidaturesHelper
end

app/helpers/city_helper.rb
module CityHelper
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/views/reviews/_form.html.erb
<%= form_for(review) do |f| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :note %>
    <%= f.text_field :note %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Note</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.note %></td>
        <td><%= review.description %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Note:</strong>
  <%= @review.note %>
</p>

<p>
  <strong>Description:</strong>
  <%= @review.description %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>